"""
Markdown Report Exporter
"""

def export_markdown():

    with open("reports/report.md","w") as file:

        file.write("# Security Report\n")

        file.write("\nGenerated by Security Log Analyzer\n")

    print("Markdown report generated.")
